 * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jph/.local/lib/python3.10/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 853, in run_command
    run_simple(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 950, in inner
    srv = make_server(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 782, in make_server
    return ThreadedWSGIServer(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.10/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jph/.local/lib/python3.10/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jph/.local/lib/python3.10/site-packages/flask/cli.py", line 853, in run_command
    run_simple(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 950, in inner
    srv = make_server(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 782, in make_server
    return ThreadedWSGIServer(
  File "/home/jph/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.10/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
